name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
      - name: Build Mod
        run: |
          cd jni
          ndk-build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-menu
          path: jni/libs/
          
